Repository School-of-Company/Expo-Client, pull requests merged in 2024-11, with the labels that each got.

#14 🔀 박람회 생성 페이지 제작
  src/app/(pages)/create-exhibition/page.tsx
  src/entities/SMS/index.tsx
  src/entities/create-exhibition/index.tsx
  src/entities/create-exhibition/model/useAddressSearch.ts
  src/entities/create-exhibition/model/useTrainingInputs.ts
  src/entities/create-exhibition/ui/ExpoInput/index.tsx
  src/entities/create-exhibition/ui/ImageInput/index.stories.ts
  src/entities/create-exhibition/ui/ImageInput/index.tsx
  src/entities/create-exhibition/ui/SearchAddress/index.tsx
  src/entities/create-exhibition/ui/TrainingModule/index.tsx
  src/entities/signIn/ui/SignInForm/index.tsx
  src/entities/signUp/ui/SignUpForm/index.tsx
  src/shared/assets/icons/Location.tsx
  src/shared/assets/icons/Picture.tsx
  src/shared/assets/icons/Plus.tsx
  src/shared/assets/icons/index.mdx
  src/shared/assets/icons/index.tsx
  src/shared/types/global.d.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/TextArea/index.stories.ts
  src/shared/ui/TextArea/index.tsx
  src/views/create-exhibition/index.tsx
  src/views/create-exhibition/ui/createExhibition/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/create-exhibition/index.tsx
  src/widgets/create-exhibition/model/api.ts
  src/widgets/create-exhibition/model/useExhibitionForm.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 🎨 Type: Publishing

#17 🔀 간단한 변경 사항 적용
  src/app/(pages)/expo-manage/page.tsx
  src/entities/expo-manage/index.tsx
  src/entities/expo-manage/ui/TableFooter/index.tsx
  src/entities/expo-manage/ui/TableHeader/index.tsx
  src/entities/expo-manage/ui/TableItem/index.tsx
  src/entities/layout/Header/model/navigationItems.ts
  src/shared/ui/Button/index.stories.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/SmallButton/index.tsx
  src/shared/ui/WhiteButton/index.tsx
  src/shared/ui/index.tsx
  src/views/expo-manage/index.tsx
  src/views/expo-manage/ui/expo-manage/index.tsx
  src/widgets/expo-detail/model/useExpoActionPanel.ts
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/expo-manage/index.tsx
  src/widgets/expo-manage/ui/FilterTab/index.tsx
  src/widgets/expo-manage/ui/TableForm/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple

#18 🔀 회원가입 페이지 로직 제작
  package-lock.json
  package.json
  src/app/api/auth/signup/route.ts
  src/app/api/auth/sms/route.ts
  src/entities/signIn/ui/SignInForm/index.tsx
  src/entities/signUp/model/checkSmsCode.ts
  src/entities/signUp/model/sendSms.ts
  src/entities/signUp/model/showError.ts
  src/entities/signUp/model/signup.ts
  src/entities/signUp/model/useTimer.ts
  src/entities/signUp/ui/SignUpForm/index.tsx
  src/shared/libs/apiClient.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/Input/index.tsx
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor, ✨ Feature

#19 🔀 로그인 페이지 로직 제작
  src/app/api/auth/signin/route.ts
  src/app/api/auth/tokenReissue/route.ts
  src/entities/signIn/model/showError.ts
  src/entities/signIn/model/signin.ts
  src/entities/signIn/ui/SignInForm/index.tsx
  src/shared/libs/apiClient.ts
  src/shared/libs/getRefresh.ts
Labels: ✨ Feature

#20 🔀 auth 페이지 간단 사항 변경
  src/entities/signIn/api/signin.ts
  src/entities/signIn/ui/SignInForm/index.tsx
  src/entities/signIn/ui/SignupPrompt/index.tsx
  src/entities/signUp/api/checkSmsCode.ts
  src/entities/signUp/api/sendSms.ts
  src/entities/signUp/api/signup.ts
  src/entities/signUp/model/useTimer.ts
  src/entities/signUp/ui/SignUpForm/index.tsx
  src/views/signIn/ui/signIn/index.tsx
  src/views/signUp/ui/signUp/index.tsx
Labels: ⚡️ Simple

#21 🔀 박람회 생성 페이지 리팩토링
  src/entities/create-exhibition/model/useAddressSearch.ts
  src/entities/create-exhibition/ui/ExpoInput/index.tsx
  src/entities/create-exhibition/ui/ImageInput/index.stories.ts
  src/entities/create-exhibition/ui/ImageInput/index.tsx
  src/entities/create-exhibition/ui/SearchAddress/index.tsx
  src/entities/create-exhibition/ui/TrainingModule/index.tsx
  src/shared/libs/getRefresh.ts
  src/shared/ui/Input/index.tsx
  src/shared/ui/TextArea/index.stories.ts
  src/shared/ui/TextArea/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/create-exhibition/api/expoApi.ts
  src/widgets/create-exhibition/api/imageApi.ts
  src/widgets/create-exhibition/api/kakaoApi.ts
  src/widgets/create-exhibition/model/api.ts
  src/widgets/create-exhibition/model/changeDate.ts
  src/widgets/create-exhibition/model/convertAddressToCoordinates.ts
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/model/uploadImage.ts
  src/widgets/create-exhibition/model/useExhibitionForm.ts
  src/widgets/create-exhibition/types/type.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: ♻️ Refactor

#22 🔀 박람회 리스트 조회 페이지 통신
  next.config.mjs
  src/app/(pages)/expo-detail/[id]/page.tsx
  src/entities/main/ui/ExpoListItem/index.stories.ts
  src/entities/main/ui/ExpoListItem/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
Labels: ✨ Feature, 📬 Type: API

#23 🔀 박람회 디테일 페이지 통시 진행
  src/app/(pages)/expo-detail/[id]/page.tsx
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
Labels: ✨ Feature, 📬 Type: API

#25 🔀 테이블 컴포넌트 변경
  package-lock.json
  package.json
  src/entities/expo-manage/index.tsx
  src/entities/expo-manage/ui/TableFooter/index.tsx
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/Table/TableHeader/index.tsx
  src/shared/ui/Table/TableItem/index.tsx
  src/shared/ui/Table/index.tsx
  src/views/expo-manage/ui/expo-manage/index.tsx
  src/widgets/expo-manage/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple

#26 🔀 어드민 페이지 제작
  src/app/(pages)/admin/page.tsx
  src/app/api/admin/[admin_id]/route.ts
  src/app/api/admin/route.ts
  src/app/api/expo/[expo_id]/route.ts
  src/entities/admin/index.tsx
  src/entities/admin/ui/AdminProfile/index.tsx
  src/entities/signIn/api/signin.ts
  src/shared/assets/icons/Check.tsx
  src/shared/assets/icons/Trash.tsx
  src/shared/assets/icons/index.mdx
  src/shared/assets/icons/index.tsx
  src/shared/assets/png/Profile.png
  src/shared/model/footerActions.ts
  src/shared/types/ SignUp/type.ts
  src/shared/types/Expo/type.ts
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/Table/TableHeader/index.tsx
  src/shared/ui/Table/TableItem/index.tsx
  src/views/admin/index.tsx
  src/views/admin/ui/Admin/index.tsx
  src/views/expo-manage/ui/expo-manage/index.tsx
  src/widgets/admin/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
Labels: ✨ Feature, 🎨 Type: Publishing, 📬 Type: API

#27 🐛expo 리스트 이미지 변경
  src/entities/main/ui/ExpoListItem/index.tsx
Labels: ⚡️ Simple

#28 ♻️ 연수 생성 페이지 리팩토링
  src/app/api/expo/route.ts
  src/app/api/image/route.ts
  src/app/api/map/route.ts
  src/entities/signIn/api/signin.ts
  src/widgets/create-exhibition/api/convertAddressToCoordinates.ts
  src/widgets/create-exhibition/api/createExhibition.ts
  src/widgets/create-exhibition/api/expoApi.ts
  src/widgets/create-exhibition/api/imageApi.ts
  src/widgets/create-exhibition/api/kakaoApi.ts
  src/widgets/create-exhibition/api/uploadImage.ts
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/model/uploadImage.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: ♻️ Refactor, 📬 Type: API

#29 🔀 박람회 생성 페이지 변경사항 반영
  src/entities/create-exhibition/index.tsx
  src/entities/create-exhibition/ui/ImageInput/index.tsx
  src/entities/create-exhibition/ui/SearchAddress/index.tsx
  src/entities/create-exhibition/ui/WarningMessage/index.tsx
  src/shared/assets/icons/Location.tsx
  src/shared/assets/icons/Picture.tsx
  src/shared/assets/icons/Warning.tsx
  src/shared/assets/icons/index.mdx
  src/shared/assets/icons/index.tsx
  src/shared/ui/Input/index.stories.ts
  src/shared/ui/Input/index.tsx
  src/widgets/create-exhibition/model/changeDate.ts
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/model/useAddressSearch.ts
  src/widgets/create-exhibition/types/type.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 🎨 Type: Publishing

#30 🐛 input 타입 에러
  src/shared/ui/Input/index.tsx
Labels: 🐞 Bug

#31 🔀 연수 생성 로직 제작
  src/app/api/standard/list/[expo_id]/route.ts
  src/app/api/training/list/[expo_id]/route.ts
  src/entities/create-exhibition/ui/ExpoInput/index.tsx
  src/entities/create-exhibition/ui/Modal/index.tsx
  src/entities/create-exhibition/ui/TrainingModule/index.tsx
  src/shared/assets/icons/Check.tsx
  src/shared/model/selectUserType.ts
  src/shared/ui/CheckBox/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/SelectUserType/index.tsx
  src/shared/ui/index.tsx
  src/widgets/create-exhibition/api/createStandard.ts
  src/widgets/create-exhibition/api/createTraining.ts
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/types/type.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 1️⃣ Priority: High, ✨ Feature, 🎨 Type: Publishing, 📬 Type: API

#32 🐛 맵 생성 버그 해결
  src/entities/create-exhibition/ui/Modal/index.tsx
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
Labels: ⚡️ Simple, 🐞 Bug

#33 🔀 박람회 연수 불러오기
  src/app/api/standard/program/[expo_id]/route.ts
  src/app/api/training/program/[expo_id]/route.ts
  src/entities/expo-detail/ui/ContentListText/index.tsx
  src/entities/expo-detail/ui/ContentText/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
Labels: ✨ Feature

#34 🔀 신청 폼 제작
  src/app/(pages)/application/[id]/page.tsx
  src/app/api/form/[expo_id]/route.ts
  src/app/api/form/pre-standard/[expo_id]/route.ts
  src/app/api/form/standard/[expo_id]/route.ts
  src/app/api/form/trainee/[expo_id]/route.ts
  src/entities/SMS/index.tsx
  src/entities/application/index.tsx
  src/entities/application/ui/Input/index.tsx
  src/entities/application/ui/RadioGroup/index.tsx
  src/shared/ui/Input/index.tsx
  src/shared/ui/PageHeader/index.tsx
  src/shared/ui/index.tsx
  src/views/application/ui/application/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/application/api/formApi.ts
  src/widgets/application/model/applicationFormHandler.ts
  src/widgets/application/types/type.ts
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/application/ui/form/ApplicationForm/standard/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
Labels: ✨ Feature

#35 🔀 역할 체크 추가
  src/app/api/expo/route.ts
  src/app/api/form/[expo_id]/route.ts
  src/app/api/form/pre-standard/[expo_id]/route.ts
  src/app/api/form/standard/[expo_id]/route.ts
  src/app/api/form/trainee/[expo_id]/route.ts
  src/app/api/standard/list/[expo_id]/route.ts
  src/app/api/standard/program/[expo_id]/route.ts
  src/app/api/tokenCheck/route.ts
  src/app/api/training/list/[expo_id]/route.ts
  src/app/api/training/program/[expo_id]/route.ts
  src/shared/components/ClientInitializer.tsx
  src/shared/stores/useStore.ts
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/layout/ui/Header/index.tsx
Labels: ✨ Feature

#37 🔀 신청 폼 라우팅
  src/app/(pages)/application/[id]/[type]/page.tsx
  src/shared/ui/Modal/index.tsx
  src/views/application/ui/application/index.tsx
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
Labels: ✨ Feature

#38 🔀 일반 유저 헤더 제작
  src/entities/layout/Header/model/navigationItems.ts
  src/entities/layout/Header/model/useNavigation.ts
Labels: ✨ Feature

#40 🔀 프로그램 폼 테이블 제작
  src/app/(pages)/program/[expo_id]/page.tsx
  src/app/(pages)/program/page.tsx
  src/entities/expo-detail/model/useKakaoMap.ts
  src/entities/program/index.tsx
  src/entities/program/ui/ProgramNavigation/index.tsx
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/views/program/index.tsx
  src/views/program/ui/Program/index.tsx
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/program/index.tsx
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: ✨ Feature, 📬 Type: API
