Repository School-of-Company/Expo-Client, pull requests merged in 2024-12, with the labels that each got.

#45 🔀 간단한 디자인 변경
  src/app/loading.tsx
  src/entities/layout/Header/model/navigationItems.ts
  src/entities/main/ui/ExpoListItem/index.tsx
  src/shared/model/footerActions.ts
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
Labels: ⚡️ Simple, 🎨 Type: Publishing

#46 🔀 폼 api들 연결
  src/app/api/application/[trainingPro_id]/route.ts
  src/app/api/sms/qr/route.ts
  src/entities/application/ui/TrainingRadioGroup/index.tsx
  src/widgets/application/types/type.ts
  src/widgets/application/ui/form/ApplicationForm/standard/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
Labels: ✨ Feature

#47 🔀 프로그램 연수 신청 api 수정
  src/app/api/training/application/[trainingPro_id]/route.ts
  src/entities/application/ui/TrainingRadioGroup/index.tsx
Labels: 🐞 Bug

#48 🔀 데이터 가공
  src/entities/signIn/ui/SignupPrompt/index.tsx
  src/entities/signUp/api/signup.ts
  src/shared/ui/Table/TableItem/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
Labels: ⚡️ Simple

#49 🔀 간단한 기능 개선 진행
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple

#50 🔀 박람회 생성 라우팅 진행
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: ♻️ Refactor

#51 🔀 신청폼 라우팅 진행
  src/widgets/application/ui/form/ApplicationForm/standard/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
Labels: ⚡️ Simple

#52 🔀 Qr 코드 사이즈 변경
  src/shared/model/printUtils.ts
Labels: ⚡️ Simple, 🎨 Type: Publishing

#53 🔀 1차 api 변경 (tanstack query로 변경)
  .eslintrc.json
  package-lock.json
  package.json
  src/app/api/expo/route.ts
  src/shared/hocs/withLoading.tsx
  src/shared/libs/TanstackProviders.tsx
  src/shared/types/expo-detail/type.ts
  src/shared/ui/Loading/index.tsx
  src/shared/ui/index.tsx
  src/widgets/expo-detail/api/getExpoDetail.ts
  src/widgets/expo-detail/model/useExpoDetail.ts
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
  src/widgets/main/api/getExpoList.ts
  src/widgets/main/model/useExpoList.ts
  src/widgets/main/ui/ExpoListContainer/index.tsx
Labels: ♻️ Refactor

#54 ♻️ 어드민 페이지 api -> tanstack query로 변경
  src/shared/model/footerActions.ts
  src/shared/types/ SignUp/type.ts
  src/shared/types/admin/type.ts
  src/shared/types/main/type.ts
  src/widgets/admin/api/getAdminData.ts
  src/widgets/admin/model/category.ts
  src/widgets/admin/model/useAdminData.ts
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/main/api/getExpoList.ts
  src/widgets/main/model/useExpoList.ts
Labels: ♻️ Refactor

#55 ♻️ 프로그램 페이지 tanstack-query로 변경
  src/shared/types/program-detail/type.ts
  src/shared/types/program/type.ts
  src/widgets/program-detail/api/getProgramDetailData.ts
  src/widgets/program-detail/model/useProgramDetailData.ts
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
  src/widgets/program/api/getProgramData.ts
  src/widgets/program/model/useProgramData.ts
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: ♻️ Refactor

#56 ♻️ route api에서 tanstack query api로 변경
  src/shared/types/expo-manage/type.ts
  src/widgets/expo-manage/api/getExpoManageData.ts
  src/widgets/expo-manage/model/category.ts
  src/widgets/expo-manage/model/useExpoData.ts
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
Labels: ♻️ Refactor

#57 🔀 간단한 변경사항 적용
  src/shared/ui/SelectUserType/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/program/model/category.ts
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: ⚡️ Simple, ⚡️performance, 🐞 Bug

#61 🔀 console.log 제거
  src/app/api/admin/[admin_id]/route.ts
  src/app/api/expo/[expo_id]/route.ts
  src/app/api/sms/qr/route.ts
  src/app/api/training/list/[expo_id]/route.ts
  src/shared/components/ClientInitializer.tsx
  src/shared/model/footerActions.ts
  src/widgets/application/ui/form/ApplicationForm/standard/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
  src/widgets/create-exhibition/api/convertAddressToCoordinates.ts
  src/widgets/create-exhibition/model/useAddressSearch.ts
Labels: ⚡️ Simple

#62 🔀 회원가입 페이지 리팩토링 진행
  src/entities/signUp/api/checkSmsCode.ts
  src/entities/signUp/api/getCheckSmsCode.ts
  src/entities/signUp/api/postSendSms.ts
  src/entities/signUp/api/postSignup.ts
  src/entities/signUp/api/sendSms.ts
  src/entities/signUp/api/signup.ts
  src/entities/signUp/model/useCheckSmsCode.ts
  src/entities/signUp/model/useSendSms.ts
  src/entities/signUp/model/useSignup.ts
  src/entities/signUp/model/useTimer.ts
  src/entities/signUp/ui/SignUpForm/index.tsx
Labels: ⚡️performance, 🐞 Bug, 📬 Type: API

#64 ♻️ 회원가입 페이지 sms 개선
  src/entities/signUp/api/getCheckSmsCode.ts
  src/entities/signUp/model/useCheckSmsCode.ts
  src/entities/signUp/model/useSendSms.ts
  src/entities/signUp/model/useTimer.ts
  src/entities/signUp/ui/SignUpForm/index.tsx
  src/shared/ui/Loading/index.tsx
Labels: ♻️ Refactor, 🐞 Bug

#65 🔀 로딩 페이지 개선
  src/shared/hocs/withLoading.tsx
  src/shared/ui/Loading/index.tsx
  src/views/admin/ui/Admin/index.tsx
  src/views/expo-detail/api/getExpoDetail.ts
  src/views/expo-detail/model/useExpoDetail.ts
  src/views/expo-detail/model/useMockExpoDetail.ts
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug, 🎨 Type: Publishing, 📬 Type: API

#67 박람회 생성 캐싱 이슈 해결
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 1️⃣ Priority: High, ✨ Feature, 🐞 Bug
