Repository School-of-Company/Expo-Client, pull requests merged in 2025-04, with the labels that each got.

#116 detail 페이지 퍼블리싱
  src/entities/expo-detail/api/getAddressFromCoords.ts
  src/entities/expo-detail/index.tsx
  src/entities/expo-detail/model/useAddressQuery.ts
  src/entities/expo-detail/ui/ContentListText/index.tsx
  src/entities/expo-detail/ui/ContentText/index.tsx
  src/entities/expo-detail/ui/ShowLocation/index.tsx
  src/shared/assets/icons/ArrowLeft.tsx
  src/shared/assets/svg/Share.tsx
  src/shared/ui/Button/index.stories.ts
  src/shared/ui/Button/index.tsx
  src/shared/ui/DetailHeader/index.tsx
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
  src/widgets/layout/ui/Header/index.tsx
  tailwind.config.ts
Labels: 🎨 Type: Publishing

#120 sms 전송 로직 변경
  src/shared/assets/icons/ArrowLeft.tsx
  src/shared/types/sms/index.ts
  src/shared/ui/DetailHeader/index.tsx
  src/shared/ui/PageHeader/index.tsx
  src/shared/ui/TextArea/index.tsx
  src/shared/ui/index.tsx
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/views/form/ui/FormEditor/index.tsx
  src/widgets/SMS/api/sendSMS.ts
  src/widgets/SMS/model/useSendSMS.ts
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
  src/widgets/signup/ui/SignUpForm/index.tsx
Labels: ♻️ Refactor

#122 qr 스캔 방식 변경
  src/app/api/server/[...path]/route.ts
  src/app/api/server/token/[...path]/route.ts
  src/shared/model/footerActions.ts
  src/shared/model/printUtils.ts
  src/shared/types/name-tag/type.ts
  src/widgets/name-tag/api/patchAttendUser.ts
  src/widgets/name-tag/model/usePatchAttendUserMutation.ts
  src/widgets/name-tag/ui/NameTagForm/index.tsx
Labels: ♻️ Refactor, 🐞 Bug

#123 폼 생성 라우트 방식 변경
  src/app/(pages)/expo-created/[expo_id]/page.tsx
  src/shared/ui/FormTypeModal/index.tsx
  src/views/expo-created/index.tsx
  src/views/expo-created/ui/ExpoCreated/index.tsx
  src/views/form/create/model/useCreateApplicationForm.ts
  src/views/form/create/model/useCreateFormMutation.ts
  src/views/form/create/model/useCreateSurveyForm.ts
  src/views/form/model/formCreateRouter.ts
  src/views/form/ui/FormEditor/index.tsx
  src/widgets/exhibition/create/model/useCreateExhibitionMutation.ts
  src/widgets/expo-created/index.tsx
  src/widgets/expo-created/ui/ExpoCreatedContainer/index.tsx
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
Labels: ⚡️ Simple, 🎨 Type: Publishing

#126 간단한 변경 사항 적용
  src/app/(pages)/expo-manage/[expo_id]/page.tsx
  src/app/(pages)/program/[expo_id]/page.tsx
  src/app/(pages)/program/detail/[program_id]/page.tsx
  src/app/api/image/route.ts
  src/app/api/map/change-geo/route.ts
  src/entities/exhibition/ui/ImageInput/index.tsx
  src/shared/assets/icons/Museum.tsx
  src/shared/hocs/withLoading.tsx
  src/shared/model/sortedData.ts
  src/shared/types/exhibition/create/type.ts
  src/shared/types/exhibition/edit/type.ts
  src/shared/types/exhibition/type.ts
  src/shared/ui/CheckBox/index.tsx
  src/shared/ui/Loading/index.tsx
  src/views/SMS/ui/SMS/index.tsx
  src/views/admin/ui/Admin/index.tsx
  src/views/application/ui/application/index.tsx
  src/views/exhibition/create/ui/createExhibition/index.tsx
  src/views/exhibition/edit/api/getAddress.ts
  src/views/exhibition/edit/model/useExpoData.ts
  src/views/exhibition/edit/ui/editExhibition/index.tsx
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/views/expo-manage/ui/expo-manage/index.tsx
  src/views/form/create/ui/createForm/index.tsx
  src/views/form/edit/ui/EditForm/index.tsx
  src/views/form/ui/FormEditor/index.tsx
  src/views/main/ui/main/index.tsx
  src/views/name-tag/ui/NameTag/index.tsx
  src/views/program-detail/ui/ProgramDetail/index.tsx
  src/views/program/ui/Program/index.tsx
  src/views/signup/ui/signUp/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/exhibition/api/convertAddressToCoordinates.ts
  src/widgets/exhibition/create/model/handleCreateExhibitionFormSubmit.ts
  src/widgets/exhibition/create/model/useCreateExhibitionMutation.ts
  src/widgets/exhibition/edit/model/handleEditExhibitionFormSubmit.ts
  src/widgets/exhibition/edit/model/useEditExhibitionMutation.ts
  src/widgets/exhibition/model/useAddressSearch.ts
  src/widgets/exhibition/ui/ExhibitionForm/index.tsx
  src/widgets/expo-detail/ui/ExpoDetailLayout/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/main/ui/EmptyExpoList/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
  src/widgets/name-tag/ui/NameTagForm/index.tsx
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: ♻️ Refactor, ⚡️ Simple, 🐞 Bug

#127 토큰 재발급 로직제작
  package-lock.json
  package.json
  src/app/api/auth/signin/route.ts
  src/app/api/auth/sms/route.ts
  src/app/api/auth/tokenReissue/route.ts
  src/shared/libs/apiClient.ts
  src/shared/libs/clearAuthCookies.ts
  src/shared/libs/setAuthCookies.ts
  src/shared/types/axios.d.ts
  src/widgets/main/ui/ExpoListContainer/index.tsx
  tsconfig.json
Labels: ✨ Feature, 📬 Type: API

#129 토큰 재발급 로직을 route handler에서 단독적으로 동작하도록 변경
  src/app/api/auth/deleteUserAccount/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signin/route.ts
  src/app/api/excel/[expo_id]/route.ts
  src/app/api/image/route.ts
  src/app/api/server/[...path]/route.ts
  src/app/api/server/token/[...path]/route.ts
  src/middleware.ts
  src/shared/api/getExpoDetail.ts
  src/shared/api/getExpoStandard.ts
  src/shared/api/getExpoTraining.ts
  src/shared/libs/apiClient.ts
  src/shared/libs/clearAuthCookies.ts
  src/shared/libs/cookie/deleteCookies.ts
  src/shared/libs/cookie/setAuthCookies.ts
  src/shared/libs/handler/baseHandler.ts
  src/shared/libs/handler/error.ts
  src/shared/libs/handler/refreshAccessToken.ts
  src/shared/libs/handler/request.ts
  src/shared/libs/handler/response.ts
  src/shared/libs/handler/token.ts
  src/shared/libs/handler/tokenHandler.ts
  src/shared/libs/handler/type.ts
  src/shared/libs/http/clientInstance.ts
  src/shared/libs/http/clientTokenInstance.ts
  src/shared/libs/http/serverInstance.ts
  src/shared/libs/setAuthCookies.ts
  src/shared/model/footerActions.ts
  src/views/form/create/api/createApplicationForm.ts
  src/views/form/create/api/createSurveyForm.ts
  src/views/form/edit/api/editApplicationForm.ts
  src/views/form/edit/api/editSurveyForm.ts
  src/views/form/edit/api/getEditApplicationForm.ts
  src/views/form/edit/api/getEditSurveyForm.ts
  src/widgets/SMS/api/sendSMS.ts
  src/widgets/admin/api/deleteExpoApi.ts
  src/widgets/admin/api/getAdminData.ts
  src/widgets/admin/api/getExpoList.ts
  src/widgets/admin/api/getRequestSignUp.ts
  src/widgets/admin/api/postAdminApi.ts
  src/widgets/application/api/getApplicationForm.ts
  src/widgets/application/api/getSurveyForm.ts
  src/widgets/application/api/postApplication.ts
  src/widgets/exhibition/api/uploadImage.ts
  src/widgets/exhibition/create/api/createExhibition.ts
  src/widgets/exhibition/edit/api/editExhibition.ts
  src/widgets/expo-manage/api/getExpoManageData.ts
  src/widgets/main/api/getExpoList.ts
  src/widgets/main/ui/ExpoListContainer/index.tsx
  src/widgets/name-tag/api/patchAttendUser.ts
  src/widgets/program-detail/api/getProgramDetailData.ts
  src/widgets/program-detail/api/patchStandardAttendance.ts
  src/widgets/program-detail/api/patchTrainingAttendance.ts
  src/widgets/program/api/getProgramData.ts
  src/widgets/signup/api/getCheckSmsCode.ts
  src/widgets/signup/api/postSendSms.ts
  src/widgets/signup/api/postSignup.ts
Labels: ♻️ Refactor

#124 조회하기 페이지 페이징 + 날짜선택 기능 제작
  src/app/(pages)/exhibition/edit/[id]/page.tsx
  src/app/(pages)/expo-detail/[id]/page.tsx
  src/entities/expo-manage/index.tsx
  src/entities/expo-manage/ui/DateButton/index.tsx
  src/entities/expo-manage/ui/SearchTab/index.tsx
  src/shared/api/getExpoDetail.ts
  src/shared/api/getExpoStandard.ts
  src/shared/api/getExpoTraining.ts
  src/shared/assets/icons/ArrowDown.tsx
  src/shared/assets/icons/ArrowLeft.tsx
  src/shared/assets/icons/ArrowRight.tsx
  src/shared/types/expo-manage/type.ts
  src/shared/ui/FormTypeModal/index.tsx
  src/shared/ui/NavigationBar/index.tsx
  src/shared/ui/SelectUserType/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/index.tsx
  src/views/exhibition/edit/model/useExpoData.ts
  src/views/exhibition/edit/ui/editExhibition/index.tsx
  src/views/expo-detail/model/useExpoDetail.ts
  src/views/expo-detail/ui/expo-detail/index.tsx
  src/widgets/exhibition/edit/api/editExhibition.ts
  src/widgets/exhibition/edit/model/handleEditExhibitionFormSubmit.ts
  src/widgets/exhibition/edit/model/useEditExhibitionMutation.ts
  src/widgets/expo-detail/ui/ExpoActionPanel/index.tsx
  src/widgets/expo-manage/api/getExpoManageData.ts
  src/widgets/expo-manage/model/category.ts
  src/widgets/expo-manage/model/useExpoData.ts
  src/widgets/expo-manage/model/useExpoDetailQuery.ts
  src/widgets/expo-manage/ui/DateContainer/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
Labels: ✨ Feature

#132 참가자 & 연수자 액셀 다운로드
  src/shared/model/footerActions.ts
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/Table/TableItem/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
Labels: ✨ Feature

#133 aws ec2 t3 small에 cd하는 스크립트 작성
  .github/workflows/cd.yml
Labels: 🌏 Deploy

#135 cd 워크 플로우 develop 반영
  .github/workflows/cd.yml
Labels: 🐞 Bug

#136 간단한 application 간격 변경
  .github/workflows/ci.yml
  src/views/application/ui/application/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
Labels: 🎨 Type: Publishing

#137 변경 사항을 배포 브랜치에 반영합니다
  .github/workflows/ci.yml
  src/views/application/ui/application/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
Labels: 🌏 Deploy

#138 x축 스크롤 이슈 해결
  src/views/form/ui/FormEditor/index.tsx
  src/views/onsite-qr/ui/OnciteQrPage/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/exhibition/ui/ExhibitionForm/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
  src/widgets/name-tag/ui/NameTagForm/index.tsx
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: 🐞 Bug

#140 x축 스크롤 이슈
  src/entities/application/ui/EtcOption/index.tsx
Labels: 🎨 Type: Publishing

#141 스타일 업데이트 적용#1
  src/entities/exhibition/ui/ExpoInput/index.tsx
  src/entities/form/ui/FormTypeSelect/index.tsx
  src/entities/form/ui/PrivacyConsentForm/index.tsx
  src/shared/ui/FormTypeModal/index.tsx
  src/shared/ui/SmallButton/index.tsx
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/ToggleButton/index.tsx
  src/views/form/model/selectOptionData.tsx
  src/widgets/exhibition/ui/ExhibitionForm/index.tsx
  src/widgets/form/ui/FormContainer/index.tsx
Labels: 🎨 Type: Publishing

#142 스타일 업데이트 2
  src/entities/form/ui/CheckBox/index.tsx
  src/entities/form/ui/DeleteButton/index.tsx
  src/entities/form/ui/RequiredToggle/index.tsx
  src/shared/styles/datepicker-custom.css
  src/shared/ui/Table/TableFooter/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
Labels: 🎨 Type: Publishing

#143 변경 사항을 매인 브랜치에 반영
  src/entities/application/ui/EtcOption/index.tsx
  src/entities/exhibition/ui/ExpoInput/index.tsx
  src/entities/form/ui/CheckBox/index.tsx
  src/entities/form/ui/DeleteButton/index.tsx
  src/entities/form/ui/FormTypeSelect/index.tsx
  src/entities/form/ui/PrivacyConsentForm/index.tsx
  src/entities/form/ui/RequiredToggle/index.tsx
  src/shared/libs/handler/token.ts
  src/shared/styles/datepicker-custom.css
  src/shared/ui/FormTypeModal/index.tsx
  src/shared/ui/SmallButton/index.tsx
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableForm/index.tsx
  src/shared/ui/ToggleButton/index.tsx
  src/views/form/model/selectOptionData.tsx
  src/views/form/ui/FormEditor/index.tsx
  src/views/onsite-qr/ui/OnciteQrPage/index.tsx
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/exhibition/ui/ExhibitionForm/index.tsx
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
  src/widgets/form/ui/FormContainer/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
  src/widgets/name-tag/ui/NameTagForm/index.tsx
  src/widgets/program-detail/ui/ProgramDetailForm/index.tsx
  src/widgets/program/ui/ProgramForm/index.tsx
Labels: 🌏 Deploy

#144 토큰 재발급 로직 개선
  package-lock.json
  package.json
  src/shared/libs/handler/error.ts
  src/shared/libs/handler/token.ts
  src/shared/libs/handler/tokenHandler.ts
Labels: ♻️ Refactor

#146 ec2 health check기능 제작
  src/app/(pages)/health/page.tsx
Labels: ✨ Feature

#147 만족도 조사폼 쿼리 스트링 설정
  src/entities/application/ui/OptionContainer/index.tsx
  src/entities/application/ui/SentenceOption/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
Labels: ✨ Feature

#148 간단한 디자인 변경사항 적용
  src/entities/admin/ui/AdminProfile/index.tsx
  src/entities/application/ui/ApplicationPhoneOption/index.tsx
  src/entities/application/ui/DropDownOption/index.tsx
  src/entities/exhibition/ui/Modal/index.tsx
  src/entities/expo-detail/ui/ContentText/index.tsx
  src/entities/expo-manage/ui/FilterTab/index.tsx
  src/entities/program/ui/ProgramNavigation/index.tsx
  src/shared/assets/icons/Check.tsx
  src/shared/assets/icons/Logout.tsx
  src/shared/types/main/type.ts
  src/shared/ui/NavigationBar/index.tsx
  src/shared/ui/SelectUserType/index.tsx
  src/shared/ui/SmallButton/index.tsx
  src/shared/ui/SortFilter/index.stories.ts
  src/shared/ui/SortFilter/index.tsx
  src/shared/ui/Table/TableFooter/index.tsx
  src/shared/ui/Table/TableItem/index.tsx
  src/widgets/admin/model/types.ts
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
  src/widgets/expo-manage/ui/DateContainer/index.tsx
  src/widgets/main/ui/ExpoListContainer/index.tsx
  src/widgets/main/ui/FormFilter/index.tsx
Labels: ⚡️ Simple

#149 로그아웃 버튼 스타일 수정
  next.config.mjs
  src/entities/admin/ui/AdminProfile/index.tsx
Labels: ⚡️ Simple, 🎨 Type: Publishing

#151 feat: LRUCache => redis 적용
  package-lock.json
  package.json
  src/app/api/auth/signin/route.ts
  src/shared/libs/cookie/setAuthCookies.ts
  src/shared/libs/handler/error.ts
  src/shared/libs/handler/refreshAccessToken.ts
  src/shared/libs/handler/request.ts
  src/shared/libs/handler/token.ts
  src/shared/libs/handler/tokenHandler.ts
  src/shared/libs/redis/lock.ts
  src/shared/libs/redis/redis.ts
  src/shared/types/redlock.d.ts
Labels: ♻️ Refactor
