Repository School-of-Company/Expo-Client, pull requests merged in 2025-01, with the labels that each got.

#68 🔀 excel 다운로드 제작
  src/app/api/excel/[expo_id]/route.ts
  src/shared/model/footerActions.ts
  src/shared/ui/Table/TableFooter/index.tsx
Labels: ⚡️performance, 🎨 Type: Publishing, 📬 Type: API

#74 🔀 pdf 출력 기능 제거
  src/shared/model/footerActions.ts
  src/shared/ui/Table/TableFooter/index.tsx
Labels: ⚡️ Simple

#73 🔀문자 발송 추가
  src/app/(pages)/sms/[id]/[authority]/page.tsx
  src/app/api/sms/message/[expo_id]/route.ts
  src/shared/ui/Modal/index.tsx
  src/widgets/SMS/api/sendSMS.ts
  src/widgets/SMS/model/useSendSMS.ts
  src/widgets/SMS/ui/SMSContainer/index.tsx
  src/widgets/application/ui/ApplicationLayout/index.tsx
Labels: 📬 Type: API

#75 🔀 로그아웃 기능 제작
  src/app/api/auth/logout/route.ts
  src/entities/admin/api/deleteLogout.ts
  src/entities/admin/model/useLogout.ts
  src/entities/admin/ui/AdminProfile/index.tsx
  src/shared/assets/icons/Logout.tsx
  src/shared/assets/icons/index.mdx
  src/shared/assets/icons/index.tsx
  src/widgets/admin/ui/AdminPageWrapper/index.tsx
Labels: ✨ Feature

#76 🔀 유저 탈퇴 기능 제작
  src/app/api/admin/route.ts
  src/entities/admin/api/deleteUserAccount.ts
  src/entities/admin/model/useDeleteUserAccount.ts
  src/entities/admin/ui/AdminProfile/index.tsx
Labels: ✨ Feature

#78 🔀 정적 폼 생성 제작
  src/app/(pages)/create-form/page.tsx
  src/entities/create-exhibition/ui/ExpoInput/index.tsx
  src/entities/create-form/index.tsx
  src/entities/create-form/ui/CheckBoxOption/index.tsx
  src/entities/create-form/ui/CreateFormButton/index.tsx
  src/entities/create-form/ui/DeleteButton/index.tsx
  src/entities/create-form/ui/DropDownOption/index.tsx
  src/entities/create-form/ui/FormTitle/index.tsx
  src/entities/create-form/ui/FormTypeSelect/index.tsx
  src/entities/create-form/ui/MultipleChoiceOption/index.tsx
  src/entities/create-form/ui/PictureOption/index.tsx
  src/entities/create-form/ui/RequiredToggle/index.tsx
  src/entities/create-form/ui/TextOption/index.tsx
  src/shared/assets/icons/ArrowUp.tsx
  src/shared/assets/icons/CheckBoxIcon.tsx
  src/shared/assets/icons/DropDown.tsx
  src/shared/assets/icons/FormPicture.tsx
  src/shared/assets/icons/MultipleChoic.tsx
  src/shared/assets/icons/Trash.tsx
  src/shared/assets/icons/Typing.tsx
  src/shared/assets/icons/index.mdx
  src/shared/assets/icons/index.tsx
  src/shared/assets/svg/Circle.tsx
  src/shared/assets/svg/Squere.tsx
  src/shared/assets/svg/index.tsx
  src/shared/types/create-form/type.ts
  src/shared/ui/AddItemButton/index.tsx
  src/shared/ui/ToggleButton/index.tsx
  src/shared/ui/index.tsx
  src/views/create-form/index.tsx
  src/views/create-form/model/selectOptionData.tsx
  src/views/create-form/ui/createForm/index.tsx
  src/widgets/create-form/ui/FormContainer/index.tsx
Labels: ✨ Feature, 🎨 Type: Publishing

#79 🔀 api url 변경
  src/app/api/application/[expo_id]/route.ts
  src/app/api/application/field/[expo_id]/route.ts
  src/app/api/application/field/standard/[expo_id]/route.ts
  src/app/api/application/pre-standard/[expo_id]/route.ts
  src/shared/types/expo-manage/type.ts
  src/widgets/application/api/formApi.ts
  src/widgets/application/model/applicationFormHandler.ts
  src/widgets/application/types/type.ts
  src/widgets/application/ui/form/ApplicationForm/standard/index.tsx
  src/widgets/application/ui/form/ApplicationForm/trainee/index.tsx
Labels: 📬 Type: API

#82 🔀 유저 조회 페이지 검색 기능 제작
  src/app/api/participant/[expo_id]/route.ts
  src/app/api/trainee/[expo_id]/route.ts
  src/entities/expo-manage/index.tsx
  src/entities/expo-manage/ui/SearchTab/index.tsx
  src/shared/ui/SelectUserType/index.tsx
  src/widgets/expo-manage/api/getExpoManageData.ts
  src/widgets/expo-manage/model/useExpoData.ts
  src/widgets/expo-manage/ui/ExpoManageForm/index.tsx
Labels: ✨ Feature

#81 🔀 현장 qr코드 생성
  package-lock.json
  package.json
  src/entities/name-tag/ui/NameTagHeader/index.tsx
  src/shared/ui/QrModal/index.tsx
  src/shared/ui/index.tsx
  src/widgets/name-tag/ui/NameTagForm/index.tsx
Labels: ✨ Feature

#84 🔀 박람회 생성 변경
  src/app/api/standard/list/[expo_id]/route.ts
  src/app/api/training/list/[expo_id]/route.ts
  src/entities/create-exhibition/ui/ExpoInput/index.tsx
  src/entities/create-exhibition/ui/Modal/index.tsx
  src/entities/create-exhibition/ui/TrainingModule/index.tsx
  src/shared/model/formErrorUtils.ts
  src/shared/types/create-exhibition/type.ts
  src/views/create-exhibition/ui/createExhibition/index.tsx
  src/widgets/create-exhibition/api/convertAddressToCoordinates.ts
  src/widgets/create-exhibition/api/createExhibition.ts
  src/widgets/create-exhibition/api/createStandard.ts
  src/widgets/create-exhibition/api/createTraining.ts
  src/widgets/create-exhibition/model/exhibitionFormHandler.ts
  src/widgets/create-exhibition/model/useExhibitionMutation.ts
  src/widgets/create-exhibition/ui/ExhibitionForm/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️performance, 🐞 Bug

#85 🔀 폼 생성 api 통신 진행
  src/app/api/form/[expo_id]/route.ts
  src/views/create-form/api/createForm.ts
  src/views/create-form/model/useCreateForm.ts
  src/views/create-form/ui/createForm/index.tsx
Labels: ✨ Feature, 📬 Type: API
